language: python

python:
  - '3.5'
  - '3.6'
  - '3.7'

before_install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - export PATH=$PATH:$HOME/miniconda/bin
  # Useful for debugging any issues with conda
  - conda info -a

install:
  - 'conda create --yes -n libkge python=$TRAVIS_PYTHON_VERSION'
  - 'source activate libkge'
  - 'sh install.sh'
  - 'pip install pytest pytest-cov'
  - 'pip install codecov'
  - 'pip install -e .[test,ci]'
  - 'python setup.py install'

script:
  - 'pytest --cov-report=xml --cov=libkge tests'

after_success:
  - 'codecov'
